# Generated by Django 5.1.1 on 2024-12-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movies",
            name="download_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movies",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="movies",
            name="thumbnail_video_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
