# Generated by Django 5.1.1 on 2024-12-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0002_movies_download_link_movies_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movies",
            name="auther_name",
            field=models.CharField(default="Movies_Lover", max_length=100),
        ),
        migrations.AddField(
            model_name="movies",
            name="create_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
