# Generated by Django 5.1.1 on 2024-12-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0003_movies_auther_name_movies_create_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="movies",
            name="release_date",
            field=models.CharField(default="2000/12/20", max_length=100),
        ),
    ]
